# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simpleserve}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Ryan Rauh}]
  s.date = %q{2011-08-06}
  s.description = %q{type `/> simpleserve` into the command line and bam... it turns it into a web server}
  s.email = %q{rauh.ryan@gmail.com}
  s.executables = [%q{simpleserve}]
  s.files = [
    "VERSION",
    "bin/simpleserve",
    "rakefile"
  ]
  s.homepage = %q{http://github.com/rauhryan/simpleserve}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.7}
  s.summary = %q{Turn any directory into a static web server with one beautify command}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

